name: Update Issues Label

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: label update
      uses: garganshu/github-label-updater@v1.0.0
      with:
        owner: ${{secrets.OWNER}}
        repo: ${{secrets.REPO}}
        token: ${{secrets.TOKEN}}
        filter-labels: ready-for-review
        remove-labels: ready-for-review
        remove-all-labels: false
        add-labels: fixed,enhancement